In [13]:
import numpy as np

In [14]:
dim = 4
M = np.random.randn(dim, dim)
M = M + M.T  # 对称化以保证本征分解存在
print(M)

lm, u = np.linalg.eig(M)
print('\n Eigenvalues:')
print(lm)

print('\n Eigenvectors:')
print(u)

[[-1.91917762 -0.53948154 -0.36872538 -0.61485743]
 [-0.53948154 -0.89703284 -2.89696976  1.87971844]
 [-0.36872538 -2.89696976  1.64887179 -0.37084167]
 [-0.61485743  1.87971844 -0.37084167 -5.12963582]]

 Eigenvalues:
[-5.94298658 -2.90295773 -1.20156739  3.75053722]

 Eigenvectors:
[[ 0.07809956  0.63699787 -0.76667823 -0.01840288]
 [-0.38901082  0.58289398  0.431028    0.5684365 ]
 [-0.10007863  0.44233509  0.3767093  -0.80772151]
 [ 0.91244469  0.24250358  0.29070512  0.15532946]]


In [15]:
print('\n Check the orthogonality of U')
print(u.dot(u.T))


 Check the orthogonality of U
[[ 1.00000000e+00 -1.66533454e-16 -1.66533454e-16  0.00000000e+00]
 [-1.66533454e-16  1.00000000e+00  3.33066907e-16 -8.32667268e-17]
 [-1.66533454e-16  3.33066907e-16  1.00000000e+00  1.45716772e-16]
 [ 0.00000000e+00 -8.32667268e-17  1.45716772e-16  1.00000000e+00]]


In [16]:
print('\n The error of the eigenvalue decomposition = ')
M1 = u.dot(np.diag(lm)).dot(u.T)
err = np.linalg.norm(M - M1)
print(err)

# 练习：编写程序完成如下任务
# 1. 验证u的每一列都是矩阵M的本征向量
# 2. 验证U第n列给出的向量对应的本征值为lm的第n个元素


 The error of the eigenvalue decomposition = 
3.1908049232143108e-15
