In [1]:
import numpy as np

In [2]:
dim = 4
M = np.random.randn(dim, dim)
M = M + M.T  # 对称化以保证本征分解存在; .T等价于.transpose(1,0)
print(M)

lm, u = np.linalg.eig(M)
print('\n Eigenvalues:')
print(lm)

print('\n Eigenvectors:')
print(u)

[[-1.27769334  1.11414703  0.56194405 -0.91706935]
 [ 1.11414703 -2.6444184   0.74454762 -0.65349964]
 [ 0.56194405  0.74454762  0.04997731 -1.03090405]
 [-0.91706935 -0.65349964 -1.03090405  3.94811025]]

 Eigenvalues:
[ 4.53597758 -3.31389346  0.09266001 -1.23876832]

 Eigenvectors:
[[ 0.20003974  0.44893232 -0.33364643 -0.80444014]
 [ 0.14323051 -0.88556564 -0.27847394 -0.34309004]
 [ 0.26320184  0.11914803 -0.83042381  0.47636629]
 [-0.93284185 -0.00608435 -0.34860956 -0.09077689]]


In [3]:
print('\n Check the orthogonality of U')
print(u.dot(u.T))


 Check the orthogonality of U
[[ 1.00000000e+00  1.38777878e-17  5.55111512e-17 -2.35922393e-16]
 [ 1.38777878e-17  1.00000000e+00 -5.55111512e-17 -1.17961196e-16]
 [ 5.55111512e-17 -5.55111512e-17  1.00000000e+00 -2.77555756e-17]
 [-2.35922393e-16 -1.17961196e-16 -2.77555756e-17  1.00000000e+00]]


In [4]:
print('\n The error of the eigenvalue decomposition = ')
M1 = u.dot(np.diag(lm)).dot(u.T)
err = np.linalg.norm(M - M1)
print(err)

# 练习：编写程序完成如下任务
# 1. 验证u的每一列都是矩阵M的本征向量
# 2. 验证U第n列给出的向量对应的本征值为lm的第n个元素


 The error of the eigenvalue decomposition = 
2.8037596640948706e-15
