In [1]:
import BasicFun as bf
import numpy as np
from scipy.sparse.linalg import eigsh

# 相关函数在BasicFun.py文件定义

# 定义二自旋反铁磁海森堡模型
H2 = bf.heisenberg_hamilt([1, 1, 1], [0, 0, 0])

e1 = np.linalg.eigh(H2)[0]
print('利用numpy中eigh函数，求得的哈密顿量全部能谱 = ')
print(e1)

e2, v2 = eigsh(H2, k=1, which='LM')
print('\n利用scipy中eigsh函数，求得的哈密顿量基态能 = ')
print(e2)

e0, gs = bf.ED_ground_state([H2.reshape(2, 2, 2, 2)], [[0, 1]])
print('\n利用基态算法，求得的哈密顿量基态能 = ')
print(e0)


print('\n利用scipy中eigsh函数，求得的哈密顿量基态 = ')
print(v2.reshape(-1, ))
print('\n利用基态算法，求得的哈密顿量基态 = ')
print(gs.reshape(-1, ))


利用numpy中eigh函数，求得的哈密顿量全部能谱 = 
[-0.75  0.25  0.25  0.25]

利用scipy中eigsh函数，求得的哈密顿量基态能 = 
[-0.75]

利用基态算法，求得的哈密顿量基态能 = 
[-0.75]

利用scipy中eigsh函数，求得的哈密顿量基态 = 
[-1.92217103e-17 -7.07106781e-01  7.07106781e-01  1.11149644e-17]

利用基态算法，求得的哈密顿量基态 = 
[-2.10098802e-13 -7.07106781e-01  7.07106781e-01 -1.19552288e-13]
